# Generated by Django 5.1.4 on 2025-01-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=30)),
                ('telefono', models.IntegerField(max_length=20)),
                ('tipo_juridico', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=30)),
                ('nombre_usuario', models.CharField(max_length=20, unique=True)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
    ]
