# Generated by Django 5.1.4 on 2025-01-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField()),
                ('hora_ingreso', models.TimeField()),
                ('hora_egreso', models.TimeField()),
                ('cantidad_personas', models.IntegerField(max_length=2)),
                ('estado_alquiler', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('ACTIVO', 'ACTIVO'), ('CANCELADO', 'CANCELADO'), ('FINALIZADO', 'FINALIZADO')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(max_length=100)),
            ],
        ),
    ]
