# Generated by Django 5.1.4 on 2025-01-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenants',
            options={'verbose_name': 'tenant', 'verbose_name_plural': 'tenants'},
        ),
        migrations.AlterField(
            model_name='tenants',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
