# Generated by Django 5.1.4 on 2025-01-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('calle', models.CharField(max_length=30)),
                ('numero', models.IntegerField(max_length=6)),
                ('barrio', models.CharField(max_length=30)),
                ('localidad', models.CharField(max_length=20)),
                ('codigo_postal', models.IntegerField(max_length=6)),
                ('provincia', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('piso', models.IntegerField(max_length=2)),
                ('codigo_depto', models.CharField(max_length=4)),
                ('capacidad_maxima', models.IntegerField(max_length=2)),
                ('precio_por_persona', models.IntegerField(max_length=6)),
            ],
        ),
    ]
